# Generated by Django 2.2.16 on 2020-10-22 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201021_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
